server:
  port: 8080
spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  datasource:
    username: eventuser
    password: mysecret987654
    driver-class-name: com.mysql.cj.jdbc.Driver
    auto-commit: true
    url: jdbc:mysql://localhost:3306/eventsDb